# Generated by Django 3.1.3 on 2020-11-14 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotation",
            name="no_deliverable",
            field=models.BooleanField(
                default=False, verbose_name="This ticket had no deliverable"
            ),
        ),
        migrations.AddField(
            model_name="annotation",
            name="product",
            field=models.TextField(
                blank=True,
                choices=[
                    ("desktop", "Firefox desktop"),
                    ("fenix", "Firefox for Android (Fenix)"),
                    ("fennec", "Firefox for Android (Fennec)"),
                    ("fennec_ios", "Firefox for iOS"),
                    ("other_mobile", "Other mobile/non-desktop"),
                    ("many", "Many products"),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="annotation",
            name="abstract",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="annotation",
            name="deliverable",
            field=models.URLField(
                blank=True,
                help_text="URL to a deliverable for this ticket",
                max_length=8192,
            ),
        ),
    ]
