# Generated by Django 3.1.3 on 2020-11-14 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jiraticket",
            name="assignee",
            field=models.EmailField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="jiraticket",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="jiraticket",
            name="last_comment",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="jiraticket",
            name="resolved",
            field=models.DateTimeField(blank=True),
        ),
    ]
