# Generated by Django 3.1.3 on 2020-11-14 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0002_auto_20201114_0251"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jiraticket",
            name="resolved",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
