# Generated by Django 3.1.3 on 2020-11-14 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0003_auto_20201114_0254"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotation",
            name="jira_ticket",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="tickets.jiraticket"
            ),
        ),
    ]
