# Generated by Django 3.1.3 on 2020-11-17 04:35

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0003_auto_20201117_0418"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotation",
            name="artifact",
            field=models.CharField(
                blank=True,
                choices=[
                    ("dashboard", "Dashboard"),
                    ("experiment", "Experiment"),
                    ("investigation", "Investigation report"),
                ],
                max_length=1024,
            ),
        ),
        migrations.AlterField(
            model_name="annotation",
            name="abstract",
            field=models.TextField(
                blank=True, help_text="<a href='#'>How to write an abstract</a>"
            ),
        ),
        migrations.AlterField(
            model_name="annotation",
            name="tags",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated list of any additional tags you'd like to apply.",
                max_length=1024,
            ),
        ),
        migrations.AlterField(
            model_name="annotation",
            name="topic",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("accounts", "Accounts"),
                    ("activity_stream", "Activity Stream"),
                    ("bookmarks", "Bookmarks"),
                    ("devtools", "Devtools"),
                    ("download", "Download page"),
                    ("enterprise", "Enterprise"),
                    ("heartbeat", "Heartbeat"),
                    ("nav", "Navigation"),
                    ("newtab", "New tab"),
                    ("onboarding", "Onboarding"),
                ],
                max_length=1024,
                verbose_name="Topics",
            ),
        ),
    ]
