# Generated by Django 3.1.3 on 2020-11-29 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0004_auto_20201117_0435"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotation",
            name="completed_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="annotation",
            name="title",
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name="annotation",
            name="abstract",
            field=models.TextField(
                blank=True,
                help_text="<a href='https://docs.google.com/document/d/1QiymsHOvyNoaSL5GfY_9yWMOl8qAZy6yomTld3Twfws/edit'>How to write an abstract</a>",
                verbose_name="tl;dr",
            ),
        ),
    ]
