# Generated by Django 3.1.3 on 2020-11-29 23:48

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0005_auto_20201129_2329"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotation",
            name="completed_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="annotation",
            name="topic",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("accounts", "Accounts"),
                    ("activity_stream", "Activity Stream"),
                    ("bookmarks", "Bookmarks"),
                    ("devtools", "Devtools"),
                    ("download", "Download page"),
                    ("enterprise", "Enterprise"),
                    ("heartbeat", "Heartbeat"),
                    ("nav", "Navigation"),
                    ("newtab", "New tab"),
                    ("onboarding", "Onboarding"),
                ],
                help_text="Ctrl- or ⌘-click to select multiple topics",
                max_length=1024,
                verbose_name="Topics",
            ),
        ),
    ]
