# Generated by Django 3.1.3 on 2020-11-30 00:55

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0006_auto_20201129_2348"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotation",
            name="artifact",
            field=models.CharField(
                blank=True,
                choices=[
                    ("dashboard", "Dashboard"),
                    ("experiment", "Experiment"),
                    ("investigation", "Investigation report"),
                    ("survey", "Survey"),
                    ("other", "Other"),
                ],
                max_length=1024,
            ),
        ),
        migrations.AlterField(
            model_name="annotation",
            name="product",
            field=models.TextField(
                blank=True,
                choices=[
                    ("desktop", "Firefox desktop"),
                    ("fenix", "Firefox for Android (Fenix)"),
                    ("fennec", "Firefox for Android (Fennec)"),
                    ("fennec_ios", "Firefox for iOS"),
                    ("other_mobile", "Other mobile/non-desktop"),
                    ("web", "Web properties"),
                    ("many", "Many products"),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="annotation",
            name="topic",
            field=multiselectfield.db.fields.MultiSelectField(
                blank=True,
                choices=[
                    ("accounts", "Accounts"),
                    ("activity_stream", "Activity Stream"),
                    ("addons", "Add-ons"),
                    ("bookmarks", "Bookmarks"),
                    ("devtools", "Devtools"),
                    ("download", "Download page"),
                    ("enterprise", "Enterprise"),
                    ("geo", "Geolocation"),
                    ("heartbeat", "Heartbeat"),
                    ("nav", "Navigation"),
                    ("newtab", "New tab"),
                    ("marketing", "Marketing campaign"),
                    ("onboarding", "Onboarding"),
                    ("pwmgr", "Password manager"),
                    ("payments", "Payments"),
                    ("percperf", "Perceived performance"),
                    ("perf", "Performance"),
                    ("platform", "Platform"),
                    ("pocket", "Pocket"),
                    ("privacy", "Privacy"),
                    ("search", "Search"),
                    ("security", "Security"),
                    ("services", "Services"),
                    ("tp", "Tracking Protection"),
                    ("vpn", "VPN"),
                ],
                help_text="Ctrl- or ⌘-click to select multiple topics",
                max_length=1024,
                verbose_name="Topics",
            ),
        ),
    ]
