# Generated by Django 3.1.3 on 2020-11-30 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0007_auto_20201130_0055"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotation",
            name="product",
            field=models.TextField(
                blank=True,
                choices=[
                    ("desktop", "Firefox desktop"),
                    ("fenix", "Firefox for Android (Fenix)"),
                    ("fennec", "Firefox for Android (Fennec)"),
                    ("fennec_ios", "Firefox for iOS"),
                    ("other", "Other"),
                    ("web", "Web properties"),
                    ("many", "Many products"),
                ],
            ),
        ),
    ]
