"""
Django settings for jira_helper project.

Generated by 'django-admin startproject' using Django 3.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

import os
from pathlib import Path

from google.cloud import secretmanager

PROJECT_ID = os.environ.get("PROJECT_ID", "tdsmith-jira-helper")
_secret_client = secretmanager.SecretManagerServiceClient()


def _get_secret(name: str) -> str:
    fqrn = f"projects/{PROJECT_ID}/secrets/{name}/versions/latest"
    response = _secret_client.access_secret_version(request={"name": fqrn})
    return response.payload.data.decode("utf-8")


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = _get_secret("tdsmith-jira-helper-django-secret")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False if os.getenv("GAE_APPLICATION", None) else True

ALLOWED_HOSTS = [
    "tdsmith-jira-helper.wl.r.appspot.com",
]


# Application definition

INSTALLED_APPS = [
    "tickets.apps.TicketsConfig",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "crispy_forms",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "jira_helper.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "jira_helper.wsgi.application"


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

_cloudsql_path = (
    Path("/cloudsql") if os.getenv("GAE_APPLICATION", None) else BASE_DIR.parent / "run"
)

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "HOST": str(_cloudsql_path / "tdsmith-jira-helper:us-west1:jira-helper-mysql"),
        "USER": "root",
        "PASSWORD": _get_secret("tdsmith-jira-helper-mysql-root"),
        "NAME": "jira_helper",
        "OPTIONS": {"charset": "utf8mb4"},
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = "/static/"

CRISPY_TEMPLATE_PACK = "bootstrap4"
